### PR TITLE
ENH: add bornagain runner

### PR DESCRIPTION
**Pull request by andyfaff**

### CODE REVIEW

**Comment by andyfaff** [comment]
@DmitryYurov, I'm trying to create a common test suite for ORSO. Since it's early days I thought I'd just check the reflectivity calculations in refnx/refl1d/bornagain to start with. I can get refl1d and refnx to agree, but the output from bornagain is different for a couple of the tests. I'm pretty sure that the reason is the different way that bornagain and refl1d/refnx handle the roughness of a layer. Is there an easy way to convert between the different ways?

**Comment by andyfaff** [comment]
@gpospelov

**Comment by DmitryYurov** [comment]
@andyfaff, none that I know of. To my knowledge, the only simple way to reach the same result with roughness in Refnx and BA is replacing roughness with manual slicing. However, relative difference in the computed signals is below 0.1 for reasonable cases.

**Comment by andyfaff** [comment]
Is there an approach in BornAgain that can use micro-slicing rather than the de-Boer roughness approximation? The interfacial broadening isn't always roughness in origin, it could be due to interdiffusion.

**Comment by gpospelov** [comment]
There are no additional convenience methods in BornAgain to create micro slices. One has to add layers manually using SLD's he wants. We welcome any suggestions on API improvements.
Adding our new colleague to the discussion
@rbeerwerth
He recently did similar comparison.

**Comment by rbeerwerth** [comment]
As already mentioned, there is currently no mechanism in BornAgain to perform automatic slicing of general samples. However, there is a mechanism for averaging out particles, see this [tutorial](https://www.bornagainproject.org/documentation/tutorial-examples/reflectometry/material-profile-with-particles/).

Regarding the slicing, it also needs to be mentioned that BornAgain uses an inverse cosh^2 probability distribution for the interface roughness, which corresponds to a hyperbolic tangent transition function of the SLD. This is different to RefNx, and afaik refl1d as well, and can also lead to rather large differencies. If this difference is taken into account in the generation of the SLD slices, nice agreement between a roughness model and slicing is observed.
We are currently considering to implement additional roughness models and/or to make them switchable from user space.

We would also like to mention, that the current release of BornAgain contains a performance bottleneck, which will make reflectivity calculations with many layers extremely slow. This issue will be fixed in the next release, and is currently already fixed in the develop branch.

**Comment by andyfaff** [comment]
> BornAgain uses an inverse cosh^2 probability distribution for the interface roughness, which corresponds to a hyperbolic tangent transition function of the SLD.

and

> If this difference is taken into account in the generation of the SLD slices, nice agreement between a roughness model and slicing is observed.

Could I clarify something here? The Nevot-Croce approach gives the same reflectivity curves as that calculated from a micro-sliced Gaussian transition function. Is an analytic approach for calculating the reflectivity also possible for when the interfacial transition is a hyperbolic tangent? Does BornAgain use `cosh**-2` in the reflectivity calculation somehow? If I was to generate a profile using a micro-sliced `tanh`, calculating its reflectivity, would it compare exactly to a BornAgain reflectivity calculation with roughness that doesn't micro-slice?

**Comment by rbeerwerth** [comment]
> The Nevot-Croce approach gives the same reflectivity curves as that calculated from a micro-sliced Gaussian transition function.

To a good approximation, at least.

> Is an analytic approach for calculating the reflectivity also possible for when the interfacial transition is a hyperbolic tangent? 

The computation in BornAgain is essentially analytic, apart from a factor that is generally expected to be small and neglected.

> Does BornAgain use cosh**-2 in the reflectivity calculation somehow?

The use of the tanh profile implies a cosh^-2 distribution. It is not directly needed itself.

> If I was to generate a profile using a micro-sliced tanh, calculating its reflectivity, would it compare exactly to a BornAgain reflectivity calculation with roughness that doesn't micro-slice?

Yep. Assuming of course that the transition is small compared to the layer thickness.

**Comment by andyfaff** [comment]
Hmm I suspect most specular reflectometry users would be expecting to use a Gaussian distribution with an erf profile. You should make that crystal clear in the BornAgain documentation because it's not obvious.

Since the default profile for most analysis packages is erf it's going to be a little more difficult to add BA to this benchmarking suite. The most probable way forward will be to microslice (which is how refnx handles `Tanh`, `Exponential`, `Sinusoidal`, `Step`, `Linear` interfaces).

**Pull request merged**
